version: "3.8"

services:
  # Frontend сервис на React
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_SOCKET_URL=http://localhost:3001
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  # Backend сервис на FastAPI/Python
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - HOST=0.0.0.0
      - LLM_API_URL=http://host.docker.internal:11434/api
      - ALLOWED_ORIGINS=http://localhost:9090,http://localhost:3000,http://frontend:80
      - RAG_ENABLED=true
      - DEBUG=false
    volumes:
      - ./backend/data:/app/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  app-network:
    driver: bridge

# Volumes для хранения данных
volumes:
  backend-data: